# Generated by Django 5.0.2 on 2024-02-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_alter_category_options_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
    ]
