# Generated by Django 5.0.2 on 2024-02-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_remove_part_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='added_by',
        ),
    ]
