# Generated by Django 5.0.2 on 2024-02-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_alter_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='transmission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
