# Generated by Django 5.0.2 on 2024-03-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0007_part_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
