# Generated by Django 5.0.2 on 2024-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0011_remove_part_sold_remove_part_sold_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
