# Generated by Django 5.0.2 on 2024-03-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0013_remove_part_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salehistory',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
