# Generated by Django 5.0.2 on 2024-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0014_salehistory_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='salehistory',
            name='available',
            field=models.IntegerField(default=1),
        ),
    ]
